server:
  port: 8080
#  tomcat:
#    max-threads: 1

logging:
  level:
    com.asimiotech: debug
    root: info

spring:
  task:
    execution:
      pool:
        core-size: 20
        max-size: 100
        queue-capacity: 3000
      thread-name-prefix: async-thread-
